spring.application.name=ecommerce

# Caminho da conexão
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo

# Nome do usuário
spring.datasource.username=kaua

# Senha do usuário
spring.datasource.password=Kaua15111006.

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Estratégia de criação
spring.jpa.hibernate.ddl-auto=create

# Exibição do SQL
spring.jpa.show-sql=true

# Formatação do SQL
spring.jpa.properties.hibernate.format_sql=true

# Dialeto
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
